Implemented more operations for rug::Complex and rug::Rational
IntrepidPig/mexprp pull request #18
Opened 2021-08-04 23:51 UTC by autumnull

I've implemented the `ceil` and `round` methods for rug::Complex, the `nrt` method still needs to be worked out.

I also implemented `abs`, `floor`, `ceil` and `round` for rug::Rational, which i think are the last of the `Num` methods that can be implemented for that type.

2021-08-05 22:08 UTC, IntrepidPig requested changes
Thanks for the PR! I think there is a couple small errors in the `ceil` and `round` implementations, but besides that it looks good.

2021-08-05 22:28 UTC, autumnull commented on src/num/rugcomplex.rs
> +		let i = Complex::real(self).ceil_ref();
oh yeah of course, sorry about that :)

2021-08-06 00:12 UTC, IntrepidPig approved these changes

2021-08-06 00:13 UTC, merged

2021-08-06 00:13 UTC, IntrepidPig commented
Thanks!